---
#- name: Remove all items from the Dock
# shell: /usr/local/bin/dockutil --remove all

- name: Set the Dock size and position
  community.general.osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: '{{ item.type }}'
    value: '{{ item.value }}'
    state: present
  loop:
    - { key: tilesize, type: int, value: '{{ dock.size }}' }
    - { key: orientation, type: string, value: '{{ dock.position | lower }}' }
  loop_control:
    label: '{{ item.key }}'
  notify: restart dock

# Allowed code:
# 0: No Option
# 2: Mission Control
# 3: Show application windows
# 4: Desktop
# 5: Start screen saver
# 6: Disable screen saver
# 7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen
- name: Set the hot corners
  community.general.osx_defaults:
    domain: com.apple.dock
    key: '{{ item.key }}'
    type: int
    value: '{{ item.value }}'
    state: present
  loop:
    - { key: wvous-tl-corner, value: '{{ dock.hotCorners.topLeft }}' }
    - { key: wvous-tr-corner, value: '{{ dock.hotCorners.topRight }}' }
    - { key: wvous-br-corner, value: '{{ dock.hotCorners.bottomRight }}' }
    - { key: wvous-bl-corner, value: '{{ dock.hotCorners.bottomLeft }}' }
  loop_control:
    label: '{{ item.key }}'
  notify: restart dock

#- name: Set the default Dock items
#  shell: dockutil --add "{{item.path}}" --replacing "{{item.name}}"
#  loop: '{{dock.apps}}'
