---
- name: Configure Finder
  community.general.osx_defaults:
    domain: '{{ item.domain | default("com.apple.finder") }}'
    key: '{{ item.key }}'
    type: bool
    value: '{{ item.value }}'
    state: present
  loop:
    - { key: ShowHardDrivesOnDesktop, value: '{{ finder.showDriveOnDestktop }}' }
    - { key: ShowExternalHardDrivesOnDesktop, value: '{{ finder.showDriveOnDestktop }}' }
    - { key: ShowRemovableMediaOnDesktop, value: '{{ finder.showDriveOnDestktop }}' }
    - { key: AppleShowAllFiles, value: '{{ finder.showHiddenFiles }}' }
    - { key: AppleShowAllExtensions, value: '{{ finder.showFilesExtentions }}', domain: NSGlobalDomain }
    - { key: ShowStatusBar, value: '{{ finder.showStatusBarInFinder }}' }
    - { key: ShowPathbar, value: '{{ finder.showPathBarInFinder }}' }
  loop_control:
    label: '{{ item.key }}'
  notify: restart finder
