---
- hosts: mttRemoteDesktop

  pre_tasks:
    - name: Include configuration
      include_vars:
        file: debian_config.yml
        name: config
    - name: Include secret configuration
      include_vars:
        file: ansible_secrets.yml
        name: secret

  roles:
    - role: debian_system
    - role: debian_xrdp
