---
- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: '{{ item }}'
      with_first_found:
        - files:
            - macos_config.yml
          skip: true

  roles:
    - role: macos/homebrew
    - role: macos/system_settings
    - role: repos
    # - role: gantsign.visual-studio-code-extensions
    #   users:
    #     - username: '{{ user }}'
    #       visual_studio_code_extensions: '{{ vscode_exts }}'
    #       visual_studio_code_extensions_absent: []
