---

- hosts: localhost

  pre_tasks:
    - name: Include configuration
      include_vars: "{{ item }}"
      with_first_found:
        - files:
            - config.yml
          skip: true

  roles:
    - role: system_settings
    - role: homebrew
    - role: repos
    - role: gantsign.visual-studio-code-extensions
      users:
        - username: "{{ user }}"
          visual_studio_code_extensions: "{{ vscode_exts }}"
          visual_studio_code_extensions_absent: []



      
  
