---
computername: null
hostname: null
ssh_keys: []
prompt: null
nvm_lines: null
dock:
  position: BOTTOM
  size: 40
  hotCorners:
    topLeft: 2
    topRight: 2
    bottomRight: 2
    bottomLeft: 2

  apps:
    - { name: Terminal, path: /System/Applications/Utilities/Terminal.app }

finder:
  showDriveOnDestktop: 'true'
  showHiddenFiles: 'true'
  showFilesExtentions: 'true'
  showStatusBarInFinder: 'true'
  showPathBarInFinder: 'true'
