---
#- name: Remove all items from the Dock
# shell: /usr/local/bin/dockutil --remove all

- name: Reduce the size of the Dock to x points
  shell: defaults write com.apple.dock tilesize -int {{dock.size}}

- name: Show the Dock on position
  shell: /usr/local/bin/m dock position {{dock.position}}

- name: Set the default Dock items
  shell: /usr/local/bin/dockutil --add "{{item.path}}" --replacing "{{item.name}}"
  loop: '{{dock.apps}}'
