---
- name: Show Drives on the Desktop
  shell: defaults write com.apple.finder ShowHardDrivesOnDesktop -bool {{finder.showDriveOnDestktop}}

- name: Show External Drives on the Desktop
  shell: defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool {{finder.showDriveOnDestktop}}

- name: Show Removable Media on the Desktop
  shell: defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool {{finder.showDriveOnDestktop}}

- name: Show Hidden Files
  shell: defaults write com.apple.finder AppleShowAllFiles -bool {{finder.showHiddenFiles}}

- name: Show File Extensions
  shell: defaults write NSGlobalDomain AppleShowAllExtensions -bool {{finder.showFilesExtentions}}

- name: Show the Status Bar in Finder
  shell: defaults write com.apple.finder ShowStatusBar -bool {{finder.showStatusBarInFinder}}

- name: Show the Path Bar in Finder
  shell: defaults write com.apple.finder ShowPathbar -bool {{finder.showPathBarInFinder}}

- name: Restart Finder
  shell: killall Finder
